# Generated by Django 5.1.5 on 2025-04-05 09:23

import Petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petstagramuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture', validators=[Petstagram.photos.validators.validate_file_size]),
        ),
    ]
