# Generated by Django 5.1.5 on 2025-04-05 09:19

import Petstagram.pets.validators
import Petstagram.photos.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('personal_photo', models.ImageField(upload_to='pet_images', validators=[Petstagram.photos.validators.validate_file_size])),
                ('date_of_birth', models.DateField(validators=[Petstagram.pets.validators.validate_past_date])),
                ('animal_type', models.CharField(max_length=30)),
                ('specie', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('distinguishing_marks', models.CharField(max_length=50)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
